export const generalStrings = {
  general: {
    appName: "Turnaround",
    welcome: "Welcome to Turnaround",
    loading: "Loading...",
    error: "An error occurred",
    success: "Operation successful",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    print: "Print",
    export: "Export",
    import: "Import",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    previous: "Previous",
    confirm: "Confirm",
    reject: "Reject",
    approve: "Approve",
    close: "Close",
    apply: "Apply",
    reset: "Reset",
    yes: "Yes",
    no: "No",
  },
  auth: {
    login: "Login",
    logout: "Logout",
    signUp: "Sign Up",
    forgotPassword: "Forgot Password",
    resetPassword: "Reset Password",
    changePassword: "Change Password",
    twoFactorAuth: "Two-Factor Authentication",
    rememberMe: "Remember Me",
    loginWithGoogle: "Login with Google",
    loginWithMicrosoft: "Login with Microsoft",
    loginWithFacebook: "Login with Facebook",
    loginWithApple: "Login with Apple",
    verifyEmail: "Verify Email",
    resendVerificationEmail: "Resend Verification Email",
  },
  navigation: {
    dashboard: "Dashboard",
    reports: "Reports",
    settings: "Settings",
    profile: "Profile",
    help: "Help",
    about: "About",
    notifications: "Notifications",
    messages: "Messages",
    logout: "Logout",
  },
  dashboard: {
    overview: "Overview",
    recentActivity: "Recent Activity",
    quickActions: "Quick Actions",
    keyMetrics: "Key Metrics",
    notifications: "Notifications",
    tasks: "Tasks",
    calendar: "Calendar",
    analytics: "Analytics",
  },
  crm: {
    customers: "Customers",
    leads: "Leads",
    opportunities: "Opportunities",
    contacts: "Contacts",
    accounts: "Accounts",
    activities: "Activities",
    campaigns: "Campaigns",
    customerService: "Customer Service",
    customerFeedback: "Customer Feedback",
    loyaltyProgram: "Loyalty Program",
    segmentation: "Customer Segmentation",
    relationshipManagement: "Customer Relationship Management",
  },
  sales: {
    orders: "Orders",
    quotes: "Quotes",
    invoices: "Invoices",
    payments: "Payments",
    products: "Products",
    priceLists: "Price Lists",
    discounts: "Discounts",
    salesTeam: "Sales Team",
    commissions: "Commissions",
    forecasts: "Forecasts",
    territories: "Sales Territories",
    pipeline: "Sales Pipeline",
    returns: "Returns and Refunds",
  },
  inventory: {
    items: "Items",
    stockLevels: "Stock Levels",
    warehouses: "Warehouses",
    transfers: "Transfers",
    adjustments: "Adjustments",
    reorderPoints: "Reorder Points",
    barcodes: "Barcodes",
    batches: "Batches",
    serialNumbers: "Serial Numbers",
    inventoryValuation: "Inventory Valuation",
    cycleCounts: "Cycle Counts",
    kitting: "Kitting and Bundling",
  },
  purchasing: {
    purchaseOrders: "Purchase Orders",
    vendors: "Vendors",
    receivingGoods: "Receiving Goods",
    supplierInvoices: "Supplier Invoices",
    supplierPayments: "Supplier Payments",
    rfq: "Request for Quotation",
    contractManagement: "Contract Management",
    supplierPerformance: "Supplier Performance",
    returns: "Purchase Returns",
    supplierRelationshipManagement: "Supplier Relationship Management",
  },
  manufacturing: {
    productionOrders: "Production Orders",
    billOfMaterials: "Bill of Materials",
    workOrders: "Work Orders",
    routings: "Routings",
    qualityControl: "Quality Control",
    maintenance: "Maintenance",
    capacityPlanning: "Capacity Planning",
    mrp: "Material Requirements Planning",
    costingAndPricing: "Costing and Pricing",
    productLifecycle: "Product Lifecycle Management",
  },
  hr: {
    employees: "Employees",
    departments: "Departments",
    positions: "Positions",
    payroll: "Payroll",
    timeTracking: "Time Tracking",
    leave: "Leave Management",
    performance: "Performance Management",
    recruitment: "Recruitment",
    training: "Training",
    expenses: "Expenses",
    benefits: "Employee Benefits",
    onboarding: "Onboarding",
    offboarding: "Offboarding",
    attendance: "Attendance",
  },
  finance: {
    generalLedger: "General Ledger",
    accountsReceivable: "Accounts Receivable",
    accountsPayable: "Accounts Payable",
    bankAccounts: "Bank Accounts",
    cashManagement: "Cash Management",
    budgeting: "Budgeting",
    assetManagement: "Asset Management",
    taxation: "Taxation",
    financialReporting: "Financial Reporting",
    costAccounting: "Cost Accounting",
    auditTrail: "Audit Trail",
    riskManagement: "Risk Management",
    compliance: "Compliance",
  },
  projectManagement: {
    projects: "Projects",
    tasks: "Tasks",
    timeSheets: "Time Sheets",
    resources: "Resources",
    ganttChart: "Gantt Chart",
    milestones: "Milestones",
    budgets: "Project Budgets",
    risks: "Risk Management",
    documents: "Project Documents",
    collaboration: "Team Collaboration",
  },
  support: {
    ticketManagement: "Ticket Management",
    knowledgeBase: "Knowledge Base",
    faq: "FAQ",
    livechat: "Live Chat",
    feedback: "Customer Feedback",
    escalations: "Escalations",
  },
  analytics: {
    reports: "Reports",
    dashboards: "Dashboards",
    dataVisualization: "Data Visualization",
    businessIntelligence: "Business Intelligence",
    predictiveAnalytics: "Predictive Analytics",
    kpis: "Key Performance Indicators",
  },
  settings: {
    generalSettings: "General Settings",
    userManagement: "User Management",
    rolePermissions: "Role and Permissions",
    companyProfile: "Company Profile",
    integrations: "Integrations",
    customization: "Customization",
    dataBackup: "Data Backup and Recovery",
    systemLogs: "System Logs",
    businessSettings: "Business Settings",
  },
  callToAction: {
    getStarted: "Get Started",
    learnMore: "Learn More",
    tryForFree: "Try for Free",
    requestDemo: "Request a Demo",
    contactSales: "Contact Sales",
    signUpNow: "Sign Up Now",
    upgradeAccount: "Upgrade Your Account",
    scheduleConsultation: "Schedule a Consultation",
    downloadWhitepaper: "Download Whitepaper",
    joinWebinar: "Join Our Webinar",
  },
  userProfile: {
    personalInfo: "Personal Information",
    accountSettings: "Account Settings",
    preferences: "Preferences",
    securitySettings: "Security Settings",
    activityLog: "Activity Log",
    linkedAccounts: "Linked Accounts",
    notificationSettings: "Notification Settings",
    privacySettings: "Privacy Settings",
  },
  placeholders: {
    search: {
      blunt: "Search",
      succinct: "Search {{item}}",
      verbose: "Search for {{item}}...",
    },
    selectOption: {
      blunt: "Select",
      succinct: "Select {{item}}",
      verbose: "Please select a {{item}}",
    },
    enterName: "Enter {{item}} name",
    enterEmail: "Enter email address",
    enterPassword: "Enter password",
    enterDescription: "Enter description",
    selectStatus: "Select status",
    enterApprovalReason: "Enter approval reason",
    enterRejectionReason: "Enter rejection reason",
  },
  labels: {
    name: "Name",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    city: "City",
    country: "Country",
    postalCode: "Postal Code",
    dateCreated: "Date Created",
    lastModified: "Last Modified",
    status: "Status",
    actions: "Actions",
    approvedBy: "Approved By",
    rejectedBy: "Rejected By",
    approvalDate: "Approval Date",
    rejectionDate: "Rejection Date",
    archiveDate: "Archive Date",
    processingDate: "Processing Date",
    completionDate: "Completion Date",
  },
  statuses: {
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    onHold: "On Hold",
    inProgress: "In Progress",
    scheduled: "Scheduled",
    draft: "Draft",
    published: "Published",
    approved: "Approved",
    rejected: "Rejected",
    pendingApproval: "Pending Approval",
    pendingReview: "Pending Review",
    pendingPayment: "Pending Payment",
    pendingFulfillment: "Pending Fulfillment",
    pendingDelivery: "Pending Delivery",
    pendingReturn: "Pending Return",
    pendingRefund: "Pending Refund",
    pendingVerification: "Pending Verification",
    archived: "Archived",
    processing: "Processing",
    processed: "Processed",
  },
  timeRelated: {
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    custom: "Custom Range",
    justNow: "Just now",
    momentsAgo: "Moments ago",
    minutesAgo: "{{number}} minute{{s}} ago",
    hoursAgo: "{{number}} hour{{s}} ago",
    daysAgo: "{{number}} day{{s}} ago",
    weeksAgo: "{{number}} week{{s}} ago",
    monthsAgo: "{{number}} month{{s}} ago",
    yearsAgo: "{{number}} year{{s}} ago",
  },
  pagination: {
    previous: "Previous",
    next: "Next",
    page: "Page {{page}} of {{totalPages}}",
    itemsPerPage: "Items per page",
    showing: "Showing {{start}} to {{end}} of {{total}} entries",
  },
  fileUpload: {
    dragAndDrop: "Drag and drop files here",
    or: "or",
    browseFiles: "Browse Files",
    maxFileSize: "Maximum file size: {{size}}MB",
    allowedFileTypes: "Allowed file types: {{types}}",
  },
  emptyStates: {
    noResults: {
      blunt: "No results",
      succinct: "No results found",
      verbose: "No results match your search criteria.",
    },
    noData: {
      blunt: "No data",
      succinct: "No data available",
      verbose: "There is no data available to display.",
    },
    noItems: {
      blunt: "No {{items}}",
      succinct: "No {{items}} found",
      verbose: "There are no {{items}} to display.",
    },
    startCreating: "Start creating {{items}}",
  },
} as const;